In [21]:
import numpy as np 

In [22]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [23]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [24]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [25]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[98 87 80 83 50 87]


In [26]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.7041867  0.37724174 0.51819325 0.27365702 0.36239824 0.54196279]


In [27]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.7041867  2.37724174 2.51819325 2.27365702 2.36239824 2.54196279]


In [28]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[294 261 240 249 150 261]


In [29]:
feature = np.random.randint(low=5, high=18, size=(9))
print(feature)

[17 11 17  9 16  6  6  8 11]


In [30]:
label = ((feature)/0.8) * 10
print(label)

[212.5 137.5 212.5 112.5 200.   75.   75.  100.  137.5]


In [31]:
noise = []
for i in range(9):
  n = np.random.randint(0,18)
  noise.append(label[i]*n)

print(noise)

[425.0, 1375.0, 0.0, 1687.5, 800.0, 825.0, 750.0, 1400.0, 962.5]
